### ISSUE TITLE
Problem with Texture Loader

### ISSUE THREAD

**Issue by FL32X** [AdyaGMD/GodLikeFaces#3]
When I use GodlikeFaces with Texture Loader there is this purple square instead of the difficulty face, it happens on both Windows and Android, medium and high quality, I also don't have any texture pack that changes the difficulty faces. This error only happens with non-demon difficulties
![Screenshot_20240618-202341](https://github.com/AdyaGMD/GodLikeFaces/assets/151586068/d256501a-6d74-4801-8bca-25bd8ba79b6c)

**Comment by AdyaGMD** [comment]
you should check with the developers of textureloader for that
