### ISSUE TITLE
Legendary levels glitch

### ISSUE THREAD

**Issue by Myron472** [AdyaGMD/GodLikeFaces#4]
This glitch happens on legendary rated levels below demon difficulty. Some difficulties like harder and maybe some others have this purple-black texture while other have fire ring misplaced.
![20240706033449_1](https://github.com/AdyaGMD/GodLikeFaces/assets/62944727/bb05ea75-b0ce-47d7-aede-30d00fed337b)
![20240706034529_1](https://github.com/AdyaGMD/GodLikeFaces/assets/62944727/7d8bc6ae-92b6-482d-81aa-5e5ce307d756)
![20240706034536_1](https://github.com/AdyaGMD/GodLikeFaces/assets/62944727/8de30e19-b659-485f-b0a5-98f766421044)

**Comment by RikuNova** [comment]
The Missing Texture difficulty on the 1st image is because of Texture Loader. Dunno why it causes it but it does. As for the other two, I don't know.

**Comment by AdyaGMD** [comment]
solved

**Comment by Myron472** [comment]
thanks!
